FROM python:3.9-slim

WORKDIR /app

# کپی فایل requirements.txt واحد
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# کپی فایل producer
COPY producer_nodes/app.py ./app.py
COPY .env .

CMD ["python", "app.py"]