FROM python:3.9-slim 

WORKDIR /app

# کپی فایل requirements.txt واحد (همان فایل producer)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# کپی فایل consumer
COPY consumer/consumer.py ./consumer.py
COPY .env .

CMD ["python", "consumer.py"]